name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build - Python ${{ matrix.python-version }} - ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 2
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

  release:
    runs-on: ubuntu-latest
    needs: [build]
    name: Publish release

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .

    - name: Get package version
      run: |
        python qrainbowstyle --version > version.txt
        echo "VERSION=$(cat version.txt)" | tr -d '\r\t\n' >> $GITHUB_ENV

    - name: Get latest version
      run: |
        git fetch --tags
        git fetch --prune --unshallow || true
        git describe --abbrev=0 --tags > release_version.txt
        echo "RELEASE_VERSION=$(cat release_version.txt)" | tr -d '\r\t\n' >> $GITHUB_ENV
        echo "${{env.RELEASE_VERSION}}"
    
    - name: Echo environment variables
      run: |
        echo "Uploaded package version is: "
        echo "${{env.VERSION}}"
        echo "Latest package version is:"
        echo "${{env.RELEASE_VERSION}}"
    
    - name: Create a release
      if: env.VERSION != env.RELEASE_VERSION
      
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
     
    - name: Skip release
      if: env.VERSION == env.RELEASE_VERSION
      run: |
        echo "Skipping because version does not changed"
